Support pipes and services
storybookjs/webpack-angular-types-plugin pull request #43
Opened 2023-06-28 11:08 UTC by ftr93

2023-06-28 13:36 UTC, Etienne-Buschong approved these changes

2023-06-29 07:05 UTC, kroeder requested changes
Can you remove the tag commit before I merge the PR, please?

2023-06-29 07:05 UTC, kroeder commented on package.json
> +	"version": "0.5.0",
@ftr93 you pushed a tag commit I think

Can you revert this, please?

2023-06-29 07:05 UTC, kroeder commented on packages/angular-demo/src/app/example.service.ts
> +	ngAfterContentInit() {}
Angular services only support `ngOnDestroy`

2023-06-29 07:05 UTC, kroeder commented on packages/angular-demo/src/app/example.service.ts
> +export class ExampleService {
For the sake of completeness, you should probably add `implements OnDestroy`

2023-06-29 12:09 UTC, kroeder approved these changes

2023-06-29 12:11 UTC, merged